# Generated by Django 6.0.6 on 2026-06-04 13:32

import apps.menu.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[apps.menu.validators.validate_product_image], verbose_name='Görsel'),
        ),
    ]
